version: '3.4'

networks:
  identity-network:
    name: identity-network
    driver: bridge

services:
  k8sDemo-app:
    container_name: k8sdemoappcontainer
    image: k8sdemoapp
    #build: .
    restart: always
    networks: 
      - identity-network
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on:
      - k8sDemo-api
      - k8sDemo-rabbitMq
      - k8sDemo-hub-manager
    volumes: 
      - D:\Code\K8sDemo\Certificates\:/etc/nginx/certs


  k8sDemo-api:
    container_name: k8sdemoapicontainer
    image: k8sdemoapi
    #build: .
    restart: always
    networks: 
      - identity-network
    ports:
      - 5501:5501
    depends_on:
      - k8sDemo-database
      - k8sDemo-rabbitMq
      - k8sDemo-hub-manager
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Infrastructure/Certificate/certificate.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: Password
    volumes:
      - D:\Code\K8sDemo\Certificates\:/app/Infrastructure/Certificate

  k8sDemo-hub-manager:
    container_name: k8sdemohubmanagercontainer
    image: k8sdemohubmanager
    #build: K8sDemoApi/
    restart: always
    networks: 
      - identity-network
    ports:
      - 5001:5001
    depends_on:
      - k8sDemo-database
      - k8sDemo-rabbitMq
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Infrastructure/Certificate/certificate.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: Password
    volumes:
      - D:\Code\K8sDemo\Certificates\:/app/Infrastructure/Certificate

  k8sDemo-worker:
    container_name: k8sdemoworkercontainer
    image: k8sdemoworker
    restart: always
    networks: 
      - identity-network
    depends_on:
      - k8sDemo-database
      - k8sDemo-rabbitMq
      - k8sDemo-hub-manager

  k8sDemo-database:
    container_name: k8sdemoapidbcontainer
    image: mcr.microsoft.com/mssql/server:2017-latest
    networks: 
      - identity-network
    ports:
      - 1433:1433
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Pass@Word1
    volumes:
      - D:\Code\K8sDemo\DbMount\:/var/opt/mssql

  k8sDemo-rabbitMq:
    container_name: k8sdemorabbitmqcontainer
    image: rabbitmq:3-management
    networks: 
      - identity-network
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    hostname: k8sDemo-rabbitMq

