apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: k8sdemo-database-claim0
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}
