apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-database-logs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    #ReadWriteOnce = mounted only for one pod
    - ReadWriteOnce
  hostPath:
    path: /d/logs/k8sDemo-database
  persistentVolumeReclaimPolicy: Retain