apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-database
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /D/Code/K8sDemo/DbMount
  persistentVolumeReclaimPolicy: Retain