apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-logs
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /d/logs/
  persistentVolumeReclaimPolicy: Retain