apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out .kompose
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: k8sdemo-rabbitmq
  name: k8sdemo-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: k8sdemo-rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out .kompose
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/identity-network: "true"
        io.kompose.service: k8sdemo-rabbitmq
    spec:
      containers:
        - image: masenellomarco/k8sdemorabbitmq:latest
          name: k8sdemorabbitmqcontainer
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources: {}
          volumeMounts:
            - mountPath: /home/logs
              name: k8sdemo-rabbitmq-claim0
      hostname: k8sdemo-rabbitmq
      restartPolicy: Always
      volumes:
        - name: k8sdemo-rabbitmq-claim0
          persistentVolumeClaim:
            claimName: k8sdemo-rabbitmq-claim0
status: {}
