apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8sdemo-mongodatabase-data-volume
  labels:
    type: local
    forceBinding: k8sdemo-mongodatabase-data-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  #ReadWriteOnce = mounted only for one pod
    - ReadWriteOnce
  hostPath:
    path: /d/code/k8sDemo/mongoDbMount
  persistentVolumeReclaimPolicy: Retain