apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8sdemo-app-logs-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    #ReadWriteOnce = mounted only for one pod
    - ReadWriteOnce
  hostPath:
    path: /d/logs/k8sDemo-app
  persistentVolumeReclaimPolicy: Retain