#claim logs

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: k8sdemo-logmanager-claim0
  name: k8sdemo-logmanager-claim0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
  #force selection of specific volume
    matchLabels: 
      type: local
      forceBinding: k8sdemo-logmanager-logs-volume
status: {}
