#Claims database 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: k8sdemo-mongodatabase-claim0
  name: k8sdemo-mongodatabase-claim0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    #force selection of specific volume
    matchLabels:
      type: local
      forceBinding: k8sdemo-mongodatabase-data-volume
status: {}
