apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out .kompose
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: k8sdemo-director
  name: k8sdemo-director
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: k8sdemo-director
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out .kompose
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/identity-network: "true"
        io.kompose.service: k8sdemo-director
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
          image: masenellomarco/k8sdemodirector:0.1.8172.26860
          name: k8sdemodirectorcontainer
          resources: {}
          volumeMounts:
            - mountPath: /root/.kube/
              name: kube-secret
      restartPolicy: Always
      volumes:
        - name: kube-secret
          secret:
            secretName: kube-secret
status: {}
