apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out .kompose
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: k8sdemo-worker
  name: k8sdemo-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: k8sdemo-worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out .kompose
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/identity-network: "true"
        io.kompose.service: k8sdemo-worker
    spec:
      containers:
        - image: masenellomarco/k8sdemoworker:latest
          name: k8sdemoworkercontainer
          resources: {}
      restartPolicy: Always
status: {}
