apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out .kompose
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: k8sdemo-hub-manager
  name: k8sdemo-hub-manager
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: k8sdemo-hub-manager
  type: LoadBalancer
status:
  loadBalancer: {}
