apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-api-certificates
spec:
  storageClassName: azurefile-csi
  volumeName: azurefile
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
status: {}
